bot/bot/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bot/', include('bot.urls')),
]

website/main/routes.py
import os
from datetime import datetime, timedelta
import logging

from flask import Blueprint, render_template, request, session, redirect, current_app
from .utils import register, login, get_user, update_user_data, msg
from .utils import get_history
from .utils import get_document, get_document_for_user
from .utils import click
import matplotlib.pyplot as plt
import io
from PIL import Image
from collections import Counter
from datetime import date
import re
import pandas as pd

main_bp = Blueprint('main', 
                    __name__, 
                    template_folder='templates',
                    static_folder='static', 
                    url_prefix='/main')

# index 資料夾
@main_bp.route('/login', methods = ['GET','POST'])
def login_user():
    # TODO 登入有給uuid，為什麼還要從session拿？
    status = 'T'
    if session.get('token'):
        return redirect('/main')
    if request.method == 'POST':
        account = request.form['account']
        password = request.form['password']
        msg = login(account, password)
        if msg == None:
            status = 'F'
        else:
            session['token'] = msg
            session['account'] = account
            return redirect('/main')
    return render_template('./auth/login.html', status = status)

def is_valid_email(email):
    #電子郵件格式
    pattern = r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'
    
    if re.fullmatch(pattern, email):
        return True
    else:
        return False

@main_bp.route('/signup', methods = ['GET','POST'])
def signup():
    status = 'T'
    if request.method == 'POST':
        email = request.form['email']
        account = request.form['account']
        password = request.form['password']

        if is_valid_email(email):
            status = 'True'
            text = register(email, account, password)
            message = msg(text)
            if(message == 'exists'):
                status = 'F'
        else:
            status = 'False' 
    return render_template('./auth/signup.html', status = status)

@main_bp.route('/source', methods = ['GET','POST'])
def source():
    try:
        data = request.get_json()
        source = data.get('source')
        session['source'] = source
    except:
        print('error')
    return redirect('/main')


@main_bp.route('/about', methods = ['GET','POST'])
def about():
    try:
        data = request.get_json()
        source = data.get('source')
        session['source'] = source
    except:
        print('error')
    return render_template('./main/about.html')

@main_bp.route('/', methods = ['GET','POST'])
def index():
    today = datetime(2024, 11, 23)
    # initialize session
    if session.get('source', None) is None:
        session['source'] = 'news'
    
    # Query
    is_recommend = request.args.get('is_recommend', session.get('is_recommend', 'False'))
    date = request.args.get('date', session.get('date', today.strftime('%Y-%m-%d')))
    source = request.args.get('source', session.get('source', 'news'))
    # Update session
    session['is_recommend'] = is_recommend
    session['date'] = date
    session['source'] = source
    # Process date
    _date = datetime.strptime(date, '%Y-%m-%d')
    _prev_date = _date - timedelta(days=1)
    _next_date = _date + timedelta(days=1)

    prev_date = _prev_date.strftime('%Y-%m-%d') if _prev_date > datetime(2023, 12, 31) else None
    next_date = _next_date.strftime('%Y-%m-%d') if _next_date < today else None

    news = []
    if session.get('token', None) is not None:
        news = get_document_for_user(session['token'], source, is_recommend, date)
        try:
            item_id = request.json.get('item_id')
            click(session['token'], item_id)
        except:
            print('error')
    elif is_recommend == 'False':
        news = get_document(source, date)
    session_str = '\n'.join([f'{k}: {v}' for k, v in session.items()])

    logging.info((
        f'session: \n{session_str}\n'
        f'is_recommend: {is_recommend}\n'
        f'date: {date}\n'
        f'source: {source}\n'
        f'news length: {len(news)}\n'
    ))
    return render_template('./main/show_news.html', news=news, is_recommend=is_recommend, date=date, prev_date=prev_date, next_date=next_date)

@main_bp.route('/logout')
def logout():
    session['token'] = None
    return redirect(f'/main')

@main_bp.route('/profile', methods = ['GET','POST'])
def profile():

    user = None
    history = None
    line_state = None

    if session.get('token', None) is not None:
        user = get_user(session['token'])
        session['id'] = user['uuid']
        history = get_history(session['token'], session['source'])
        line_state = os.urandom(16).hex()

        if request.method == 'POST':
            data = request.get_json()
            source = data.get('source')
            session['source'] = source

    return render_template('./main/profile.html', user=user, history=history, line_state=line_state)

@main_bp.route('/edit-profile', methods = ['GET','POST'])
def edit_profile():
    is_login = 'False'
    if session.get('token', None) is not None:
        is_login = 'True'
        user = get_user(session['token'])
        history = get_history(session['token'], session['source'])
    status = 'T'
    if request.method == 'POST':
        try:
            data = request.get_json()
            source = data.get('source')
            session['source'] = source
        except:
            account = request.form['account']
            password = request.form['password']
            email = request.form['email']
            line_id = request.form['line_id']
            
            if is_valid_email(email):
                status = 'True'
                update_user_data(session['token'], account, password, email, line_id)
            else:
                status = 'False'
    return render_template('./main/edit_profile.html', status = status, user = user, history = history, is_login = is_login)

@main_bp.route('/test', methods = ['GET'])
def test():
    return render_template('./layout/test.html')

website/main/templates/layout/auth_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Page</title>
    <!-- Bootstrap for quick styling -->
    <link rel="icon" href="{{ url_for('main.static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('main.static', filename='global.css') }}">
    <link rel="stylesheet" href="{{ url_for('main.static', filename='auth.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="container" id="main">
        <div class="row justify-content-center" style="height: 100%;">
            <!-- Login and SignUp form -->
            <div class="col-md-6 d-flex justify-content-center align-items-center login-signup-wrapper">
                <div class="login-box">
                    <!-- Centered Tab Navigation -->
                    <div class="flex justify-content-center">
                        <img src="./static/images/logo.png" alt="logo" class="w-[100px] h-[100px] user-select-none">
                    </div>
                        {% block content %}
                        {% endblock %}
                    <!-- <ul class="nav nav-tabs d-flex justify-content-center" id="myTab" role="tablist">
                        <li class="nav-item" role="presentation">
                            <a class="nav-link text-dark {{ 'active' if request.path == url_for('main.index') else '' }}" id="login-tab" href="/main" role="tab" aria-controls="login" aria-selected="true">LogIn</a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link text-dark {{ 'active' if request.path == url_for('main.signup') else '' }}" id="signup-tab" href="/main/signup" role="tab" aria-controls="signup" aria-selected="false">SignUp</a>
                        </li>
                    </ul> -->

                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">



    <!-- VANTA JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanta@0.5.24/dist/vanta.clouds.min.js"></script>
    <script>
        VANTA.CLOUDS({
            el: "body",
            mouseControls: true,
            touchControls: true,
            gyroControls: false,
            minHeight: 200.00,
            minWidth: 200.00,
            sunlightColor: 0xb36f33
        })
    </script>
</body>
</html>

website/main/templates/layout/main_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('main.static', filename='favicon.ico') }}" type="image/x-icon">
    <title>Home</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('main.static', filename='global.css') }}">
    <link rel="stylesheet" href="{{ url_for('main.static', filename='main.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
</head>
<body class="flex flex-col min-h-screen">
    <div id="particles-js" class="fixed inset-0 -z-10"></div>
    <nav id="navbar" class="sticky top-0 z-50 bg-[var(--sail-100)] border-b-2 border-gray-600 shadow-lg">
        <div class="container 2xl:max-w-7xl mx-auto flex justify-between items-center">
            <div>
                <a href="/main">
                    <img src="./static/images/logo.png" alt="logo" class="select-none w-[70px] h-[55px] ">
                </a>
            </div>
            <ul class="flex items-center gap-8 font-semibold text-gray-800">
                <a href="/main?is_recommend=True">
                    <div class="flex items-center gap-2 nav-anime hover:text-gray-600">
                        <i class="bi bi-star-fill"></i>
                        <li>推薦文章</li>
                    </div>
                </a>
                <a href="/main?is_recommend=False">
                    <div class="flex items-center gap-2 nav-anime hover:text-gray-600">
                        <i class="bi bi-newspaper"></i>
                        <li>其他文章</li>
                    </div>
                </a>
                <a href="/main/about">
                    <div class="flex items-center gap-2 nav-anime hover:text-gray-600">
                        <i class="bi bi-people-fill"></i>
                        <li>關於我們</li>
                    </div>
                </a>
                {% if session.get('token', None) %}
                    <a href="/main/profile">
                        <div class="flex items-center gap-2 nav-anime hover:text-gray-600">
                            <i class="bi bi-person-fill"></i>
                            <li>{{ session['account'] }}</li>
                        </div>
                    </a>
                {% else %}
                    <a href="/main/login">
                        <div class="flex items-center gap-2 nav-anime hover:text-gray-600">
                            <i class="bi bi-person-fill"></i>
                            <li>登入</li>
                        </div>
                    </a>
                {% endif %}
                <a href="#" id="popup-link">
                    <div class="bg-[var(--sail-500)] text-[var(--base-text-white)] flex items-center gap-2 border border-gray-800 hover:border-gray-600 px-2 py-1 rounded-lg
                        shadow-md 
                        transition transform duration-300 ease-in-out
                        hover:scale-105 hover:bg-[var(--sail-600)]
                        hover:ring-4 hover:ring-[var(--sail-200)] hover:text-[var(--base-text-white)]
                    ">
                        <li>
                            {% if session['source'] == 'all' %}
                                資料來源：全部
                            {% elif session['source'] == 'papers' %}
                                資料來源：論文
                            {% else %}
                                資料來源：新聞
                            {% endif %}
                        </li>
                        <i class="bi bi-caret-down-fill"></i>
                    </div>
                </a>
            </ul>
        </div>
    </nav>
    <main class="flex-grow">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="bg-[var(--sail-100)] p-[30px] text-gray-800">
        <div class="container mx-auto">
            <div class="flex items-center justify-center">
                <a href="#">
                    <img src="./static/images/logo.png" alt="logo" class="select-none w-[60px] h-[60px] ">
                </a>
                <p class="text-lg font-bold">文章推薦系統</p>
            </div>
            <div class="flex items-center justify-center gap-5 mt-5 mb-10">
                <a href="#" class="underline">Privacy Policy</a>
                <a href="#" class="underline">Terms of Use</a>
            </div>
            <div class="text-center mb-10">
                <p>&copy; 2024 Document Recommender System. FJU-CS113-PR-A15. All rights reserved.</p>
            </div>
        </div>
    </footer>
    <script>
        document.getElementById("popup-link").addEventListener("click", function(event) {
            event.preventDefault(); // Prevents the link from navigating away
    
            Swal.fire({
                title: '選擇資料來源',
                html: `
                    <div style="text-align: center; margin-top: 20px; justify-content: center; display: flex; flex-wrap: wrap;">
                        <div style="display: flex; flex-wrap: wrap; gap: 20px;">
                            <label class="custom-label" style="flex-basis: 45%; text-align: left;">
                                <input type="radio" name="swal-option" value="news" class="custom-radio" style="margin-right: 20px;">
                                <span class="checkmark"></span> 新聞
                            </label>
                            <label class="custom-label" style="flex-basis: 45%; text-align: left;">
                                <input type="radio" name="swal-option" value="papers" class="custom-radio" style="margin-right: 20px;">
                                <span class="checkmark"></span> 論文
                            </label>
                            <label class="custom-label" style="flex-basis: 45%; text-align: left;">
                                <input type="radio" name="swal-option" value="all" class="custom-radio" style="margin-right: 20px;">
                                <span class="checkmark"></span> 全部
                            </label>
                        </div>
                    </div>
                `,
                preConfirm: () => {
                    const selectedOption = document.querySelector('input[name="swal-option"]:checked');
                    if (!selectedOption) {
                        Swal.showValidationMessage('You need to choose something!');
                    }
                    return selectedOption ? selectedOption.value : null;
                },
                confirmButtonText: '確認',
                cancelButtonText: '取消',
                showCancelButton: true,
                customClass: {
                    popup: 'my-swal'
                }
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = `/main?source=${result.value}`;
                }
            });
        });
    </script>
    <script src="{{ url_for('main.static', filename='particles.js') }}"></script>
</body>
</html>

website/main/templates/layout/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
<!-- link, title, abstract, gattered_datetime -->

    {% with 
        link="",
        title="abc",
        abstract="123",
        gattered_datetime=""
    %}
        {% include 'components/doc_block.html' %}
    {% endwith %}
    

</div>
</body>
</html>